name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        stability: [prefer-lowest, prefer-stable]
        phpunit: [^6.0, ^7.0, ^8.0, ^9.0]

    name: PHP 7.2

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-stability-${{ matrix.stability }}-phpunit-${{ matrix.phpunit }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv, mcrypt
          coverage: none

      - name: Install Dependencies
        run: |
          composer update "phpunit/phpunit:${{ matrix.phpunit }}"
          composer install --${{ matrix.stability}} --no-interaction
      - name: Execute Tests
        run: ./vendor/bin/phpunit